---
loglevel: WARN

slack_config:
  webhook: blagh
  default_channel: "#alerts"

alertconfig:
  alert_name:
    contacts:
      - first_contact
      - second_contact
      - third_contact
    vars:
      custom_variable: 42

  capture_hc:
    contacts:
      - "@matthew.d"
      - "@jack.c"
      - "@alexs"
    vars:
      custom_message: "The System ... is down"
